@startuml instagram_webhook

!theme _none_

!include <tupadr3/common>
' !include <tupadr3/font-awesome-5/whatsapp_square>
!include <tupadr3/font-awesome-5/instagram_square>

!include <aws/common>
!include <aws/General/AWSCloud/AWSCloud>
!include <aws/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway>
!include <aws/Compute/AWSLambda/AWSLambda>
!include <aws/Compute/AWSLambda/LambdaFunction/LambdaFunction>
!include <aws/Database/AmazonDynamoDB/AmazonDynamoDB>
!include <aws/Database/AmazonDynamoDB/table/table>

left to right direction

FA5_INSTAGRAM_SQUARE(instagramWebhook, "Instagram Webhook", component, Pink)

AWSCLOUD(AWS, "AWS Cloud", cloud) {

  AMAZONDYNAMODB(dynamoDB, "DynamoDB") {
    TABLE(notificationsTable, "Interações")
  }
  
  AWSLAMBDA(apiFunctions, "Lambda") {
    LAMBDAFUNCTION(saveNotificationLambda, "Salvar Interações")
    LAMBDAFUNCTION(validaTokenLambda, "Valida Token")
  }

  AMAZONAPIGATEWAY(api, "Api Gateway") {
    component ["POST /instagram"]
    component ["GET /instagram"]
  }

}

instagramWebhook ..> ["POST /instagram"] : notifica evento
instagramWebhook <..> ["GET /instagram"] : solicita token
["GET /instagram"] <..> validaTokenLambda : valida token
["POST /instagram"] ..> saveNotificationLambda : dispara função
saveNotificationLambda ..> notificationsTable : armazena

@enduml
