@startuml diagram_wp
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml

!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml

APIGateway(webhookAPI, "Webhook API (HTTPS)", "interface com whatsapp cloud")
Lambda(webhookPost, "Recebe Notificações", "recebe notificações de mensagens")
DynamoDB(notificationsTable, "Tabela Notificações", "tabela de mensagens enviadas e recebidas")


cloud whatsappCloudApi  [
    Whatsapp API
]

whatsappCloudApi .down.> webhookAPI : notifica evento (POST /)
webhookAPI -right-> webhookPost : notifica evento (POST /)
webhookPost -right-> notificationsTable : registra mensagem enviada

@enduml
