version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "whatsapp-interface"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2xuccqpbg8b4"
s3_prefix = "whatsapp-interface"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "NotificationsTableNameParam=\"wa_Notifications\" ConnectionsTableNameParam=\"wa_Connections\" DynamoDBEndpointParam=\"\" VerifyTokenParam=\"6d4f33e1-0711-4563-9033-e71376fe3f18\" UserAccessTokenParam=\"EAACfugykhm8BACxrV9hmHQnCFKnRfAC7cXtlFUuv1zAZBjvKK1DqOSpbGaXEI8Pg3DFObCyZCyEwyOjXv8OXr9s2LBAILuBXZB6DLVznB3Cu9DV9Sxam5R4huUGn2LFsnerNCWVxZAfM6eYYdZAZBL2TPVrvfWWQ9cZCBTrORCUcLAtBm5YlEg7JVrFXsXtPRkZA2OHszys7BgZDZD\" StageParam=\"beta\""
image_repositories = []
