AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Whatsapp webhook to persiste received messages

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Description: The name of the application
    Type: String
  UserAccessTokenParam:
    Description: This is the token that authorize send whatsapp messages
    Type: String
  VerifyTokenParam:
    Description: This is the verify token value from Meta webhook set up.
    Type: String
  NotificationsTableNameParam:
    Default: wa_Notifications
    Description: The name of the table for store whatsapp notifications.
    Type: String
  DynamoDBEndpointParam:
    Type: String
    Description: URL to access dynamodb.
  StageParam:
    Description: The name of the stage
    Type: String
    Default: beta
  IssuerParam:
    Description: The token issuer
    Type: String
  UserPoolClientRefParam:
    Description: The cognito user pool client
    Type: String

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100

Resources:
  WhatsappApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageParam
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: !Sub ${AppName} - Whatsapp API
        paths: {}
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - OPTIONS
          - GET
          - POST
          - DELETE
          - PUT
        AllowOrigins:
          - "http://localhost:8080"
          - "https://*"
      Auth:
        Authorizers:
          OAuth2Authorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Ref IssuerParam
              audience:
                - !Ref UserPoolClientRefParam
        EnableIamAuthorizer: true
        DefaultAuthorizer: OAuth2Authorizer

  WebhookGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers
      Handler: handler_get.handler
      Description: This Lambda function is responsible for returning info on whatsapp verification request (setting up whatsapp endpoint)
      Environment:
        Variables:
          VERIFY_TOKEN: !Ref VerifyTokenParam
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref WhatsappApiGateway
            Auth:
              Authorizer: NONE

  WebhookPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers
      Handler: handler_post.handler
      Description: This lambda function is responsible for receiving whatsapp events and store it
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotificationsTableNameParam
      Environment:
        Variables:
          NOTIFICATIONS_TABLE_NAME: !Ref NotificationsTableNameParam
          DYNAMODB_ENDPOINT: !Ref DynamoDBEndpointParam
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            ApiId: !Ref WhatsappApiGateway
            Auth:
              Authorizer: NONE

  SentWhatsappMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers
      Handler: handler_sent_whatsapp_message.handler
      Description: Send a message to whatsapp by proxing the whatsapp API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotificationsTableNameParam
      Environment:
        Variables:
          NOTIFICATIONS_TABLE_NAME: !Ref NotificationsTableNameParam
          USER_ACCESS_TOKEN: !Ref UserAccessTokenParam
          DYNAMODB_ENDPOINT: !Ref DynamoDBEndpointParam
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /whatsapp/{apiVersion}/{phoneNumberId}/messages
            Method: POST
            ApiId: !Ref WhatsappApiGateway
            Auth:
              Authorizer: OAuth2Authorizer
