AWSTemplateFormatVersion: "2010-09-09"
Description: An base template with for common resources

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Description: Name for the authenticator resources
    Type: String
    Default: Social CRM
  StageParam:
    Description: The name of the stage
    Type: String
    Default: beta
  UserAccessTokenParam:
    Description: This is the token that authorize send whatsapp messages
    Type: String
  VerifyTokenParam:
    Description: This is the verify token value from Meta webhook set up.
    Type: String
  AssistancesTableNameParam:
    Default: sl_Assistances
    Description: The name of the table for store assistances notifications.
    Type: String
  DynamoDBEndpointParam:
    Type: String
    Description: URL to access dynamodb.
  AdminEmail:
    Description: The email used to set default admin user
    Type: String
  AdminName:
    Description: The name used to set default admin user
    Type: String
  AdminPhoneNumber:
    Description: The phone number used to set default admin user
    Type: String

Resources:
  AssistancesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref AssistancesTableNameParam
      AttributeDefinitions:
        - AttributeName: PartitionKey
          AttributeType: S
        - AttributeName: SortKey
          AttributeType: S
        - AttributeName: OpenAssistance
          AttributeType: S
      KeySchema:
        - AttributeName: PartitionKey
          KeyType: HASH
        - AttributeName: SortKey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: OpenAssistances
          KeySchema:
            - AttributeName: OpenAssistance
              KeyType: HASH
            - AttributeName: PartitionKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  Auth:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
        AdminEmail: !Ref AdminEmail
        AdminName: !Ref AdminName
        AdminPhoneNumber: !Ref AdminPhoneNumber
      TemplateURL: ./template_auth.yaml

  AssistancesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
        DynamoDBEndpointParam: !Ref DynamoDBEndpointParam
        StageParam: !Ref StageParam
        UserPoolClientRefParam: !GetAtt Auth.Outputs.UserPoolClientRef
        IssuerParam: !GetAtt Auth.Outputs.Issuer
        AssistancesTableNameParam: !Ref AssistancesTableNameParam
        AssistancesTableStreamArnParam: !GetAtt AssistancesTable.StreamArn
      TemplateURL: ./assistances/template.yaml

  WhatsappStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
        DynamoDBEndpointParam: !Ref DynamoDBEndpointParam
        StageParam: !Ref StageParam
        UserPoolClientRefParam: !GetAtt Auth.Outputs.UserPoolClientRef
        IssuerParam: !GetAtt Auth.Outputs.Issuer
        NotificationsTableNameParam: !Ref AssistancesTableNameParam
        VerifyTokenParam: !Ref VerifyTokenParam
        UserAccessTokenParam: !Ref UserAccessTokenParam
      TemplateURL: ./whatsapp/template.yaml
