AWSTemplateFormatVersion: "2010-09-09"
Description: An base template with for common resources

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AuthName:
    Description: Name for the authenticator resources
    Type: String
    Default: StudiolAuth
  AdminEmail:
    Description: The email used to set default admin user
    Type: String
  AdminName:
    Description: The name used to set default admin user
    Type: String
  AdminPhoneNumber:
    Description: The phone number used to set default admin user
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AuthName}-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: true
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireUppercase: false
          RequireNumbers: true
          RequireSymbols: false
          TemporaryPasswordValidityDays: 4
      MfaConfiguration: "OFF"
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AuthName}-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      RefreshTokenValidity: 30
      TokenValidityUnits:
        RefreshToken: days
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH

  AttendantGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Exchange messages
      GroupName: attendant
      Precedence: 0
      UserPoolId: !Ref UserPool

  AdminUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref UserPool
      Username: !Ref AdminEmail
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: !Ref AdminEmail
        - Name: phone_number
          Value: !Ref AdminPhoneNumber
        - Name: name
          Value: !Ref AdminName

  AttachAdminUserToAttendantGroup:
    Type: AWS::Cognito::UserPoolUserToGroupAttachment
    Properties:
      GroupName: !Ref AttendantGroup
      Username: !Ref AdminUser
      UserPoolId: !Ref UserPool
